name: PracticeServer
main: me.bpweber.practiceserver.PracticeServer
version: Version 1.1
authors: [bpweber, Red29, VawkeNetty, Kayaba]
softdepend: [HolographicDisplays, BarAPI, BossBarAPI, VanishNoPacket, Vault, WorldGuard, ScoreboardStats, Essentials]
loadbefore:
  [Essentials, VoxelSniper]
commands:
  giveNameTag:
  gcreate:
  toggleholodmg:
  reboot:
  speed:
  dump:
  Invsee:
  sc:
  eco:
  givePouch:
  giveCrate:
  giveKey:
  createdrop:
  tellall:
  roll:
  setrank:
  gl:
  psban:
  psunban:
  psmute:
  psunmute:
  toggle:
    aliases: [toggles]
  togglepvp:
  togglechaos:
  toggledebug:
    aliases: [debug]
  toggleff:
  add:
  del:
  delete:
  message:
    aliases: [msg, m, whisper, w, tell, t]
  reply:
    aliases: [r]
  banksee:
  logout:
  sync:
  showms:
  hidems:
  monspawn:
  killall:
  showloot:
  hideloot:
  psvanish:
  pinvite:
  paccept:
  pquit:
  pkick:
  pdecline:
  p:
  toggletrail:
  gmotd:
  gtest:
  ginfo:
  guilds:
  ga:
  guild:
  guildmenu:
  gi:
  create:
  abandon:
  invite:
  join:
  leave:
  playerinfo:
  confirm:
permissions:
   PracticeServer.group.default:
      default: true
   PracticeServer.info:
       default: true
   PracticeServer.novaguilds:
      default: true