package me.kayaba.guilds.enums;

import me.kayaba.guilds.api.basic.*;
import org.apache.commons.lang.*;
import org.bukkit.command.*;

public enum Permission {
    GUILDS_ADMIN_ACCESS,
    GUILDS_ADMIN_CONFIG_ACCESS,
    GUILDS_ADMIN_CONFIG_GET,
    GUILDS_ADMIN_CONFIG_RELOAD,
    GUILDS_ADMIN_CONFIG_RESET,
    GUILDS_ADMIN_CONFIG_SAVE,
    GUILDS_ADMIN_CONFIG_SET,
    GUILDS_ADMIN_ERROR_ACCESS,
    GUILDS_ADMIN_ERROR_LIST,
    GUILDS_ADMIN_PLAYER_ACCESS,
    GUILDS_ADMIN_PLAYER_SET_POINTS,
    GUILDS_ADMIN_GUILD_ACCESS,
    GUILDS_ADMIN_GUILD_ABANDON,
    GUILDS_ADMIN_GUILD_BANK_PAY,
    GUILDS_ADMIN_GUILD_BANK_WITHDRAW,
    GUILDS_ADMIN_GUILD_INACTIVE_UPDATE,
    GUILDS_ADMIN_GUILD_INACTIVE_CLEAN,
    GUILDS_ADMIN_GUILD_INACTIVE_LIST,
    GUILDS_ADMIN_GUILD_INVITE,
    GUILDS_ADMIN_GUILD_KICK,
    GUILDS_ADMIN_GUILD_LIST,
    GUILDS_ADMIN_GUILD_SET_LEADER,
    GUILDS_ADMIN_GUILD_SET_LIVEREGENERATIONTIME,
    GUILDS_ADMIN_GUILD_SET_LIVES,
    GUILDS_ADMIN_GUILD_SET_NAME,
    GUILDS_ADMIN_GUILD_SET_POINTS,
    GUILDS_ADMIN_GUILD_SET_TAG,
    GUILDS_ADMIN_GUILD_SET_TIMEREST,
    GUILDS_ADMIN_GUILD_SET_SLOTS,
    GUILDS_ADMIN_GUILD_PURGE,
    GUILDS_ADMIN_GUILD_TELEPORT_SELF,
    GUILDS_ADMIN_GUILD_TELEPORT_OTHER,
    GUILDS_ADMIN_GUILD_FULLINFO,
    GUILDS_ADMIN_GUILD_RESET_POINTS,
    GUILDS_ADMIN_GUILD_RANK_ACCESS,
    GUILDS_ADMIN_GUILD_RANK_LIST,
    GUILDS_ADMIN_GUILD_RANK_EDIT,
    GUILDS_ADMIN_GUILD_RANK_DELETE,
    GUILDS_ADMIN_GUILD_RANK_SET,
    GUILDS_ADMIN_RELOAD,
    GUILDS_ADMIN_SAVE,
    GUILDS_ADMIN_SAVE_NOTIFY,
    GUILDS_ADMIN_UPDATEAVAILABLE,
    GUILDS_ADMIN_CHATSPY_SELF,
    GUILDS_ADMIN_CHATSPY_OTHER,
    GUILDS_ADMIN_MIGRATE,
    GUILDS_ADMIN_NOCONFIRM,

    GUILDS_GUILD_ACCESS,
    GUILDS_GUILD_ABANDON,
    GUILDS_GUILD_LEAVE,
    GUILDS_GUILD_ALLY,
    GUILDS_GUILD_BANK_PAY,
    GUILDS_GUILD_BANK_WITHDRAW,
    GUILDS_GUILD_COMPASS,
    GUILDS_GUILD_CREATE,
    GUILDS_GUILD_EFFECT,
    GUILDS_GUILD_INVITE,
    GUILDS_GUILD_JOIN,
    GUILDS_GUILD_KICK,
    GUILDS_GUILD_PVPTOGGLE,
    GUILDS_GUILD_REQUIREDITEMS,
    GUILDS_GUILD_TOP,
    GUILDS_GUILD_WAR,
    GUILDS_GUILD_BUYLIFE,
    GUILDS_GUILD_BUYSLOT,
    GUILDS_GUILD_CHATMODE,
    GUILDS_GUILD_INFO,
    GUILDS_GUILD_LEADER,
    GUILDS_GUILD_MENU,
    GUILDS_GUILD_BOSS,
    GUILDS_GUILD_OPENINVITATION,
    GUILDS_GUILD_SET_NAME,
    GUILDS_GUILD_SET_TAG,
    GUILDS_GUILD_RANK_ACCESS,
    GUILDS_GUILD_RANK_LIST,
    GUILDS_GUILD_RANK_EDIT,
    GUILDS_GUILD_RANK_DELETE,
    GUILDS_GUILD_RANK_SET,

    GUILDS_CHAT_NOTAG,
    GUILDS_PLAYERINFO,
    GUILDS_TOOL_CHECK,
    GUILDS_TOOL_GET,
    GUILDS_ERROR,
    GUILDS_BASEGUILDS,
    GUILDS_CONFIRM;


    public boolean has(CommandSender sender) {
        return sender.hasPermission(getPath()) || sender.isOp();
    }


    public boolean has(GPlayer nPlayer) {
        return has(nPlayer.getPlayer());
    }


    public String getPath() {
        return StringUtils.replace(name(), "_", ".").toLowerCase();
    }


    public static Permission fromPath(String path) {
        try {
            return Permission.valueOf(StringUtils.replace(path, ".", "_").toUpperCase());
        } catch (Exception e) {
            return null;
        }
    }
}
